/**
 * Bileşen önizleme örnekleri (samples)
 * Saf React kütüphanesi — yalnızca bağımlılıksız bileşenlerin canlı önizlemeleri.
 * Katalog stüdyosu bu haritayı kullanır.
 */
import type { ReactNode } from "react"
import * as U from "@/components/ui"
import { Box, CreditCard, Earth, Receipt, RotateCcw, ShoppingBag } from "@/components/ui/icons"

export const SAMPLES: Record<string, ReactNode> = {
  "088": (
    <U.DateRangePickerSimple />
  ),
  "089": (
    <div className="h-64 w-full overflow-hidden rounded-md border border-black/25">
      <U.MillerColumns data={U.SAMPLE_DATA} />
    </div>
  ),
  "090": (
    <U.AccordionSimple className="w-full max-w-sm" variant="surface" divider={false} defaultValue={["a"]}>
      <U.AccordionSimpleItem itemKey="a" title="How do I place an order?" icon={<ShoppingBag />}>
        Browse our products, add items to your cart, and proceed to checkout.
      </U.AccordionSimpleItem>
      <U.AccordionSimpleItem itemKey="b" title="Can I modify or cancel my order?" icon={<Receipt />}>
        Yes, you can modify or cancel your order before it&apos;s shipped.
      </U.AccordionSimpleItem>
      <U.AccordionSimpleItem itemKey="c" title="What payment methods do you accept?" icon={<CreditCard />}>
        We accept all major credit cards, including Visa, Mastercard, and American Express.
      </U.AccordionSimpleItem>
      <U.AccordionSimpleItem itemKey="d" title="How much does shipping cost?" icon={<Box />}>
        Shipping costs vary based on your location and the size of your order.
      </U.AccordionSimpleItem>
      <U.AccordionSimpleItem itemKey="e" title="Do you ship internationally?" icon={<Earth />}>
        Yes, we ship to most countries. Please check our shipping rates and policies.
      </U.AccordionSimpleItem>
      <U.AccordionSimpleItem itemKey="f" title="How do I request a refund?" icon={<RotateCcw />}>
        If you&apos;re not satisfied, you can request a refund within 30 days of purchase.
      </U.AccordionSimpleItem>
    </U.AccordionSimple>
  ),
  "091": (
    <U.BreadcrumbsSimple className="rounded-lg bg-muted/50 px-3 py-2">
      <U.BreadcrumbsSimpleItem href="#">Home</U.BreadcrumbsSimpleItem>
      <U.BreadcrumbsSimpleItem href="#">Products</U.BreadcrumbsSimpleItem>
      <U.BreadcrumbsSimpleItem>Laptop</U.BreadcrumbsSimpleItem>
    </U.BreadcrumbsSimple>
  ),
  "092": <U.Button onPress={() => console.log("pressed")}>Click me</U.Button>,
  "093": <U.Spinner size="md" />,
  "094": <U.ButtonVariants />,
  "095": <U.ButtonSizes />,
  "096": <U.ButtonWithIcons />,
  "097": <U.ButtonIconOnly />,
  "098": <U.ButtonLoading />,
  "099": <U.ButtonLoadingState />,
  "100": <U.ButtonFullWidth />,
  "101": <U.ButtonDisabled />,
  "102": <U.ButtonSocial />,
  "103": <U.ButtonRenderFunction />,
  "104": <U.ButtonCustomVariantsDemo />,
  "105": <U.ButtonRipple />,
  "106": <U.AccordionBasic />,
  "107": <U.AccordionSurface />,
  "108": <U.AccordionWithoutSeparator />,
  "109": <U.AccordionMultiple />,
  "110": <U.AccordionDisabled />,
  "111": <U.AccordionControlled />,
  "112": <U.AccordionCustomIndicator />,
  "113": <U.AccordionRenderFunction />,
  "114": <U.AccordionFaq />,
  "115": <U.AccordionCustomStyles />,
  "116": <U.Alert />,
  "117": <U.CloseButton />,
  "118": <U.AlertBasic />,
  "119": <U.AlertCustomStyles />,
  "120": <U.AlertDialogDefault />,
  "121": <U.AlertDialogDefault />,
  "122": <U.AlertDialogStatuses />,
  "123": <U.AlertDialogPlacements />,
  "124": <U.AlertDialogSizes />,
  "125": <U.AlertDialogControlled />,
  "126": <U.AlertDialogCustomIcon />,
  "127": <U.AlertDialogCustomTrigger />,
  "128": <U.AlertDialogBackdropVariants />,
  "129": <U.AlertDialogCustomBackdrop />,
  "130": <U.AlertDialogDismissBehavior />,
  "131": <U.AlertDialogCloseMethods />,
  "132": <U.AlertDialogCustomAnimations />,
  "133": <U.AlertDialogCustomPortal />,
  "134": <U.AlertDialogCustomStyles />,
  "135": <U.Autocomplete items={[{id:"a",name:"Option A"},{id:"b",name:"Option B"}]} placeholder="Select one" selectionMode="single" />,
  "136": <U.Label>Etiket örneği</U.Label>,
  "137": <U.SearchField placeholder="Ara..." />,
  "138": <U.ListBox className="w-52"><U.ListBoxItem>Elma</U.ListBoxItem><U.ListBoxItem>Armut</U.ListBoxItem></U.ListBox>,
  "139": <U.TagGroup><U.Tag id="a">React</U.Tag><U.Tag id="b">Tailwind</U.Tag></U.TagGroup>,
  "140": <U.EmptyState title="Sonuç yok" description="Aramanızla eşleşen kayıt bulunamadı." />,
  "141": <U.Description>Açıklama metni</U.Description>,
  "142": <U.AutocompleteDefault />,
  "143": <U.AutocompleteVariants />,
  "144": <U.AutocompleteFullWidth />,
  "145": <U.AutocompleteWithDescription />,
  "146": <U.AutocompleteRequired />,
  "147": <U.AutocompleteDisabled />,
  "148": <U.AutocompleteWithDisabledOptions />,
  "149": <U.AutocompleteAllowsEmptyCollection />,
  "150": <U.AutocompleteMultipleSelect />,
  "151": <U.AutocompleteControlled />,
  "152": <U.AutocompleteControlledMultiple />,
  "153": <U.AutocompleteControlledOpenState />,
  "154": <U.AutocompleteAsynchronousFiltering />,
  "155": <U.AutocompleteOnSurface />,
  "156": <U.Avatar><U.AvatarFallback>JD</U.AvatarFallback></U.Avatar>,
  "157": <U.AvatarBasic />,
  "158": <U.AvatarSizes />,
  "159": <U.AvatarColors />,
  "160": <U.AvatarVariants />,
  "161": <U.AvatarFallbackDemo />,
  "162": <U.AvatarGroup />,
  "163": <U.AvatarCustomStyles />,
  "164": <U.Breadcrumbs><U.BreadcrumbsItem href="#">Home</U.BreadcrumbsItem><U.BreadcrumbsItem>Laptop</U.BreadcrumbsItem></U.Breadcrumbs>,
  "165": <U.BreadcrumbsBasic />,
  "166": <U.BreadcrumbsLevel2 />,
  "167": <U.BreadcrumbsLevel3 />,
  "168": <U.BreadcrumbsDisabled />,
  "169": <U.BreadcrumbsCustomSeparator />,
  "170": <U.BreadcrumbsRenderFunction />,
  "171": <U.BreadcrumbsCustomStyles />,
  "172": <U.Calendar />,
  "173": <U.CalendarBasic />,
  "174": <U.CalendarDisabled />,
  "175": <U.CalendarReadOnly />,
  "176": <U.CalendarDefaultValue />,
  "177": <U.CalendarControlled />,
  "178": <U.CalendarMinMaxDates />,
  "179": <U.CalendarUnavailableDates />,
  "180": <U.CalendarWeeksInMonth />,
  "181": <U.CalendarMultipleSelection />,
  "182": <U.CalendarFocusedValue />,
  "183": <U.CalendarWithIndicators />,
  "184": <U.CalendarCustomIcons />,
  "185": <U.CalendarMultipleMonths />,
  "186": <U.CalendarBooking />,
  "187": <U.CalendarCustomStyles />,
  "188": <U.Card className="w-64"><U.CardHeader><U.CardTitle>Kart</U.CardTitle><U.CardDescription>Açıklama</U.CardDescription></U.CardHeader></U.Card>,
  "189": <U.CardDefault />,
  "190": <U.CardVariants />,
  "191": <U.CardHorizontal />,
  "192": <U.CardWithAvatar />,
  "193": <U.CardWithImages />,
  "194": <U.CardWithForm />,
  "195": <U.CardCustomStyles />,
  "196": <U.Checkbox />,
  "197": <U.CheckboxGroup />,
  "198": <U.CheckboxBasic />,
  "199": <U.CheckboxVariants />,
  "200": <U.CheckboxFullRounded />,
  "201": <U.CheckboxDisabled />,
  "202": <U.CheckboxExternalLabel />,
  "203": <U.CheckboxWithDescription />,
  "204": <U.CheckboxDefaultSelected />,
  "205": <U.CheckboxInvalid />,
  "206": <U.CheckboxControlled />,
  "207": <U.CheckboxIndeterminate />,
  "208": <U.CheckboxForm />,
  "209": <U.CheckboxRenderProps />,
  "210": <U.CheckboxCustomIndicator />,
  "211": <U.CheckboxCustomStyles />,
  "212": <U.CheckboxGroupBasic />,
  "213": <U.CheckboxGroupOnSurface />,
  "214": <U.CheckboxGroupDisabled />,
  "215": <U.CheckboxGroupIndeterminate />,
  "216": <U.CheckboxGroupControlled />,
  "217": <U.CheckboxGroupValidation />,
  "218": <U.CheckboxGroupFeatures />,
  "219": <U.CheckboxGroupCustomIndicator />,
  "220": <U.CheckboxGroupCustomStyles />,
  "221": <U.Chip color="accent">Chip</U.Chip>,
  "222": <U.ChipBasic />,
  "223": <U.ChipVariants />,
  "224": <U.ChipStatuses />,
  "225": <U.ChipWithIcon />,
  "226": <U.ChipCustomStyles />,
  "227": <U.ColorSwatch color="#0485F7" />,
  "228": <U.ColorSlider channel="hue" defaultValue="hsl(200,100%,50%)" label="Hue" />,
  "229": <U.ColorField />,
  "230": <U.ColorArea />,
  "231": <U.ColorSwatchPicker colors={["#0485F7","#EF4444","#F59E0B","#10B981"]} />,
  "232": <U.ColorPicker />,
  "233": <U.ColorSwatchBasic />,
  "234": <U.ColorSwatchSizes />,
  "235": <U.ColorSliderBasic />,
  "236": <U.ColorSliderVertical />,
  "237": <U.ColorSliderAlpha />,
  "238": <U.ColorFieldBasic />,
  "239": <U.ColorFieldControlled />,
  "240": <U.ColorAreaBasic />,
  "241": <U.ColorAreaWithDots />,
  "242": <U.ColorSwatchPickerBasic />,
  "243": <U.ColorSwatchPickerStack />,
  "244": <U.ColorPickerControlled />,
  "245": <U.ColorPickerWithSwatches />,
  "246": <U.Combobox items={[{id:"a",name:"Option A"},{id:"b",name:"Option B"}]} placeholder="Seç..." />,
  "247": <U.ComboboxDefault />,
  "248": <U.ComboboxFullWidth />,
  "249": <U.ComboboxWithDescription />,
  "250": <U.ComboboxRequired />,
  "251": <U.ComboboxDisabled />,
  "252": <U.ComboboxWithDisabledOptions />,
  "253": <U.ComboboxControlled />,
  "254": <U.ComboboxControlledInput />,
  "255": <U.ComboboxAsyncLoading />,
  "256": <U.ComboboxDefaultSelectedKey />,
  "257": <U.ComboboxAllowsCustomValue />,
  "258": <U.ComboboxCustomFiltering />,
  "259": <U.ComboboxMultipleSelection />,
  "260": <U.ComboboxOnSurface />,
  "261": <U.ComboboxCustomStyles />,
  "262": <U.DateField />,
  "263": <U.DateFieldBasic />,
  "264": <U.DateFieldVariants />,
  "265": <U.DateFieldDisabled />,
  "266": <U.DateFieldControlled />,
  "267": <U.DatePicker />,
  "268": <U.DatePickerBasic />,
  "269": <U.DatePickerDisabled />,
  "270": <U.DatePickerControlled />,
  "271": <U.DateRangePicker />,
  "272": <U.DateRangePickerBasic />,
  "273": <U.DateRangePickerDisabled />,
  "274": <U.DateRangePickerControlled />,
  "275": <U.Drawer />,
  "276": <U.DrawerBasic />,
  "277": <U.DrawerPlacements />,
  "278": <U.DrawerNonDismissable />,
  "279": <U.DrawerScrollable />,
  "280": <U.DrawerControlled />,
  "281": <U.DrawerWithForm />,
  "282": <U.DrawerNavigation />,
  "283": <U.DrawerBackdropVariants />,
  "284": <U.DrawerCustomStyles />,
  "285": <U.TextField />,
  "286": <U.TextFieldBasic />,
  "287": <U.TextFieldOnSurface />,
  "288": <U.TextFieldWithDescription />,
  "289": <U.TextFieldRequired />,
  "290": <U.TextFieldDisabled />,
  "291": <U.TextFieldFullWidth />,
  "292": <U.TextFieldValidation />,
  "293": <U.TextFieldControlled />,
  "294": <U.TextFieldWithError />,
  "295": <U.TextFieldTextArea />,
  "296": <U.TextFieldInputTypes />,
  "297": <U.TextFieldRenderFunction />,
  "298": <U.TextFieldCustomStyles />,
  "299": <U.Input />,
  "300": <U.TextArea />,
  "301": <U.FieldError />,
  "302": <U.TextAreaBasic />,
  "303": <U.TextAreaVariants />,
  "304": <U.TextAreaOnSurface />,
  "305": <U.TextAreaFullWidth />,
  "306": <U.TextAreaControlled />,
  "307": <U.TextAreaRows />,
  "308": <U.TextAreaCustomStyles />,
  "309": <U.NumberField />,
  "310": <U.NumberFieldBasic />,
  "311": <U.NumberFieldVariants />,
  "312": <U.NumberFieldOnSurface />,
  "313": <U.NumberFieldWithDescription />,
  "314": <U.NumberFieldRequired />,
  "315": <U.NumberFieldDisabled />,
  "316": <U.NumberFieldFullWidth />,
  "317": <U.NumberFieldValidation />,
  "318": <U.NumberFieldControlled />,
  "319": <U.NumberFieldStep />,
  "320": <U.NumberFieldFormatOptions />,
  "321": <U.NumberFieldFormExample />,
  "322": <U.NumberFieldWithValidation />,
  "323": <U.NumberFieldCustomIcons />,
  "324": <U.NumberFieldChevrons />,
  "325": <U.NumberFieldRenderFunction />,
  "326": <U.NumberFieldCustomStyles />,
  "327": <U.InputBasic />,
  "328": <U.InputVariants />,
  "329": <U.InputOnSurface />,
  "330": <U.InputFullWidth />,
  "331": <U.InputTypes />,
  "332": <U.InputControlled />,
  "333": <U.InputCustomStyles />,
  "334": <U.InputGroup />,
  "335": <U.InputGroupDefault />,
  "336": <U.InputGroupVariants />,
  "337": <U.InputGroupOnSurface />,
  "338": <U.InputGroupWithLoadingSuffix />,
  "339": <U.InputGroupRequired />,
  "340": <U.InputGroupDisabled />,
  "341": <U.InputGroupFullWidth />,
  "342": <U.InputGroupWithTextPrefix />,
  "343": <U.InputGroupWithTextSuffix />,
  "344": <U.InputGroupIconPrefixTextSuffix />,
  "345": <U.InputGroupWithCopySuffix />,
  "346": <U.InputGroupIconPrefixCopySuffix />,
  "347": <U.InputGroupPasswordToggle />,
  "348": <U.InputGroupWithBadgeSuffix />,
  "349": <U.InputGroupInvalid />,
  "350": <U.InputGroupWithPrefixIcon />,
  "351": <U.InputGroupWithSuffixIcon />,
  "352": <U.InputGroupWithPrefixAndSuffix />,
  "353": <U.InputGroupWithTextArea />,
  "354": <U.InputGroupCustomStyles />,
  "355": (
    <U.InputOTP maxLength={6}>
      <U.InputOTPGroup>
        <U.InputOTPSlot index={0} />
        <U.InputOTPSlot index={1} />
        <U.InputOTPSlot index={2} />
      </U.InputOTPGroup>
      <U.InputOTPSeparator />
      <U.InputOTPGroup>
        <U.InputOTPSlot index={3} />
        <U.InputOTPSlot index={4} />
        <U.InputOTPSlot index={5} />
      </U.InputOTPGroup>
    </U.InputOTP>
  ),
  "356": <U.InputOTPBasic />,
  "357": <U.InputOTPVariants />,
  "358": <U.InputOTPOnSurface />,
  "359": <U.InputOTPDisabled />,
  "360": <U.InputOTPFourDigits />,
  "361": <U.InputOTPControlled />,
  "362": <U.InputOTPOnComplete />,
  "363": <U.InputOTPFormExample />,
  "364": <U.InputOTPWithPattern />,
  "365": <U.InputOTPWithValidation />,
  "366": <U.InputOTPCustomStyles />,
  "367": <U.Fieldset />,
  "368": <U.FieldsetBasic />,
  "369": <U.FieldsetOnSurface />,
  "370": <U.FieldsetCustomStyles />,
  "371": <U.Form />,
  "372": <U.FormBasic />,
  "373": <U.FormRenderFunction />,
  "374": <U.FormCustomStyles />,
  "375": <U.ErrorMessage />,
  "376": <U.ErrorMessageBasic />,
  "377": <U.ErrorMessageCustomStyles />,
  "378": <U.FieldErrorBasic />,
  "379": <U.FieldErrorDynamic />,
  "380": <U.FieldErrorCustom />,
  "381": <U.Slider />,
  "382": <U.SliderDefault />,
  "383": <U.SliderDisabled />,
  "384": <U.SliderVertical />,
  "385": <U.SliderRange />,
  "386": <U.SliderRenderFunction />,
  "387": <U.SliderCustomStyles />,
  "388": <U.SliderControlled />,
  "389": <U.RadioGroup />,
  "390": <U.RadioGroupBasic />,
  "391": <U.RadioGroupHorizontal />,
  "392": <U.RadioGroupVariants />,
  "393": <U.RadioGroupOnSurface />,
  "394": <U.RadioGroupDisabled />,
  "395": <U.RadioGroupControlled />,
  "396": <U.RadioGroupUncontrolled />,
  "397": <U.RadioGroupValidation />,
  "398": <U.RadioGroupCustomIndicator />,
  "399": <U.RadioGroupRenderFunction />,
  "400": <U.RadioGroupCustomStyles />,
  "401": <U.Switch />,
  "402": <U.SwitchBasic />,
  "403": <U.SwitchSizes />,
  "404": <U.SwitchWithIcons />,
  "405": <U.SwitchDisabled />,
  "406": <U.SwitchWithoutLabel />,
  "407": <U.SwitchWithDescription />,
  "408": <U.SwitchDefaultSelected />,
  "409": <U.SwitchControlled />,
  "410": <U.SwitchLabelPosition />,
  "411": <U.SwitchGroupVertical />,
  "412": <U.SwitchGroupHorizontal />,
  "413": <U.SwitchForm />,
  "414": <U.SwitchRenderProps />,
  "415": <U.SwitchRenderFunction />,
  "416": <U.SwitchCustomStyles />,
  "417": <U.ToggleButton />,
  "418": <U.ToggleButtonBasic />,
  "419": <U.ToggleButtonVariants />,
  "420": <U.ToggleButtonIconOnly />,
  "421": <U.ToggleButtonSizes />,
  "422": <U.ToggleButtonDisabled />,
  "423": <U.ToggleButtonControlled />,
  "424": <U.ToggleButtonCustomStyles />,
  "425": <U.ToggleButtonGroup />,
  "426": <U.ToggleButtonGroupBasic />,
  "427": <U.ToggleButtonGroupSizes />,
  "428": <U.ToggleButtonGroupOrientation />,
  "429": <U.ToggleButtonGroupFullWidth />,
  "430": <U.ToggleButtonGroupDisabled />,
  "431": <U.ToggleButtonGroupWithoutSeparator />,
  "432": <U.Modal />,
  "433": <U.ModalDefault />,
  "434": <U.ModalSizes />,
  "435": <U.ModalPlacements />,
  "436": <U.ModalScrollBehavior />,
  "437": <U.ModalControlled />,
  "438": <U.ModalWithForm />,
  "439": <U.ModalCustomTrigger />,
  "440": <U.ModalBackdropVariants />,
  "441": <U.ModalCustomBackdrop />,
  "442": <U.ModalDismissBehavior />,
  "443": <U.ModalCloseMethods />,
  "444": <U.ModalCustomAnimations />,
  "445": <U.ModalCustomPortal />,
  "446": <U.ModalCustomStyles />,
  "447": <U.Popover />,
  "448": <U.PopoverBasic />,
  "449": <U.PopoverWithArrow />,
  "450": <U.PopoverInteractive />,
  "451": <U.PopoverPlacement />,
  "452": <U.PopoverRenderFunction />,
  "453": <U.PopoverCustomStyles />,
  "454": <U.Tooltip />,
  "455": <U.TooltipBasic />,
  "456": <U.TooltipPlacement />,
  "457": <U.TooltipWithArrow />,
  "458": <U.TooltipCustomTrigger />,
  "459": <U.TooltipRenderFunction />,
  "460": <U.TooltipCustomStyles />,
  "461": <U.ToastProvider />,
  "462": <U.ToastDefault />,
  "463": <U.ToastSimple />,
  "464": <U.ToastVariants />,
  "465": <U.ToastCustomIndicator />,
  "466": <U.ToastPromise />,
  "467": <U.ToastCallbacks />,
  "468": <U.ToastCustomQueue />,
  "469": <U.ToastPlacements />,
  "470": <U.ToastCustomToast />,
  "471": <U.ToastCustomStyles />,
  "472": <U.Menu />,
  "473": <U.MenuDefault />,
  "474": <U.MenuWithIcons />,
  "475": <U.MenuWithDescriptions />,
  "476": <U.MenuDisabledItems />,
  "477": <U.MenuWithSections />,
  "478": <U.MenuMultipleSelection />,
  "479": <U.MenuControlled />,
  "480": <U.MenuSingleSelection />,
  "481": <U.MenuCustomTrigger />,
  "482": <U.MenuLongPress />,
  "483": <U.MenuWithKeyboardShortcuts />,
  "484": <U.Pagination />,
  "485": <U.PaginationBasic />,
  "486": <U.PaginationSizes />,
  "487": <U.PaginationDisabled />,
  "488": <U.PaginationSimple />,
  "489": <U.PaginationControlled />,
  "490": <U.PaginationWithEllipsis />,
  "491": <U.PaginationWithSummary />,
  "492": <U.PaginationCustomIcons />,
  "493": <U.PaginationCustomStyles />,
  "494": <U.Tabs />,
  "495": <U.TabsBasic />,
  "496": <U.TabsVertical />,
  "497": <U.TabsDisabled />,
  "498": <U.TabsWithSeparator />,
  "499": <U.TabsSecondary />,
  "500": <U.TabsSecondaryVertical />,
  "501": <U.TabsOverflow />,
  "502": <U.TabsRenderFunction />,
  "503": <U.TabsCustomStyles />,
  "504": <U.ButtonGroup />,
  "505": <U.ButtonGroupBasic />,
  "506": <U.ButtonGroupVariants />,
  "507": <U.ButtonGroupSizes />,
  "508": <U.ButtonGroupOrientation />,
  "509": <U.ButtonGroupWithIcons />,
  "510": <U.ButtonGroupFullWidth />,
  "511": <U.ButtonGroupDisabled />,
  "512": <U.ButtonGroupCustomStyles />,
  "513": <U.Toolbar />,
  "514": <U.ToolbarBasic />,
  "515": <U.ToolbarVertical />,
  "516": <U.ToolbarAttached />,
  "517": <U.ToolbarWithButtonGroup />,
  "518": <U.ToolbarCustomStyles />,
  "519": <U.Table />,
  "520": <U.TableBasic />,
  "521": <U.TableSecondaryVariant />,
  "522": <U.TableSorting />,
  "523": <U.TableSelection />,
  "524": <U.TableExpandableRows />,
  "525": <U.TablePagination />,
  "526": <U.TableColumnResizing />,
  "527": <U.TableEmptyState />,
  "528": <U.TableCustomCells />,
  "529": <U.TableCustomStyles />,
  "530": (
    <U.ProgressBar aria-label="Loading" className="w-64" value={60}>
      <U.ProgressBarTrack><U.ProgressBarFill /></U.ProgressBarTrack>
    </U.ProgressBar>
  ),
  "531": <U.ProgressBarBasic />,
  "532": <U.ProgressBarSizes />,
  "533": <U.ProgressBarColors />,
  "534": <U.ProgressBarWithoutLabel />,
  "535": <U.ProgressBarIndeterminate />,
  "536": <U.ProgressBarCustomValue />,
  "537": <U.ProgressBarCustomStyles />,
  "538": <U.ProgressCircle aria-label="Loading" value={60}><U.ProgressCircleSvg /></U.ProgressCircle>,
  "539": <U.ProgressCircleBasic />,
  "540": <U.ProgressCircleSizes />,
  "541": <U.ProgressCircleColors />,
  "542": <U.ProgressCircleIndeterminate />,
  "543": <U.ProgressCircleWithLabel />,
  "544": <U.ProgressCircleCustomSvg />,
  "545": <U.ProgressCircleCustomStyles />,
  "546": <U.Skeleton />,
  "547": <U.SkeletonBasic />,
  "548": <U.SkeletonTextContent />,
  "549": <U.SkeletonUserProfile />,
  "550": <U.SkeletonList />,
  "551": <U.SkeletonGrid />,
  "552": <U.SkeletonSingleShimmer />,
  "553": <U.SkeletonAnimationTypes />,
  "554": (
    <U.Meter aria-label="Storage" className="w-64" value={60}>
      <U.MeterTrack><U.MeterFill /></U.MeterTrack>
    </U.Meter>
  ),
  "555": <U.MeterBasic />,
  "556": <U.MeterSizes />,
  "557": <U.MeterColors />,
  "558": <U.MeterWithoutLabel />,
  "559": <U.MeterCustomValue />,
  "560": <U.MeterCustomStyles />,
  "561": <U.RangeCalendar />,
  "562": <U.RangeCalendarBasic />,
  "563": <U.RangeCalendarDisabled />,
  "564": <U.RangeCalendarDefaultValue />,
  "565": <U.RangeCalendarControlled />,
  "566": <U.RangeCalendarMinMax />,
  "567": <U.RangeCalendarUnavailable />,
  "568": <U.Select />,
  "569": <U.SelectDefault />,
  "570": <U.SelectVariants />,
  "571": <U.SelectFullWidth />,
  "572": <U.SelectWithDescription />,
  "573": <U.SelectRequired />,
  "574": <U.SelectDisabled />,
  "575": <U.SelectWithDisabledOptions />,
  "576": <U.SelectMultiple />,
  "577": <U.SelectControlled />,
  "578": <U.SelectCustomStyles />,
  "579": <U.TimeField />,
  "580": <U.TimeFieldBasic />,
  "581": <U.TimeFieldWithPrefixIcon />,
  "582": <U.TimeFieldWithSuffixIcon />,
  "583": <U.TimeFieldWithPrefixAndSuffix />,
  "584": <U.TimeFieldOnSurface />,
  "585": <U.TimeFieldWithDescription />,
  "586": <U.TimeFieldRequired />,
  "587": <U.TimeFieldDisabled />,
  "588": <U.TimeFieldFullWidth />,
  "589": <U.Separator />,
  "590": <U.SeparatorBasic />,
  "591": <U.SeparatorVariants />,
  "592": <U.SeparatorWithSurface />,
  "593": <U.SeparatorVertical />,
  "594": <U.SeparatorWithContent />,
  "595": <U.ScrollShadow />,
  "596": <U.ScrollShadowBasic />,
  "597": <U.ScrollShadowOrientation />,
  "598": <U.ScrollShadowShadowSize />,
  "599": <U.ScrollShadowWithCard />,
  "600": <U.ScrollShadowHideScrollBar />,
  "601": <U.ScrollShadowVisibilityChange />,
  "602": <U.Typography />,
  "603": <U.TypographyScale />,
  "604": <U.TypographyPrimitives />,
  "605": <U.TypographyProse />,
  "606": <U.TypographyRenderProps />,
  "607": <U.TypographyCustomStyles />,
  "608": <U.Kbd />,
  "609": <U.KbdBasic />,
  "610": <U.KbdVariants />,
  "611": <U.KbdNavigationKeys />,
  "612": <U.KbdInlineUsage />,
  "613": <U.KbdInstructionalText />,
  "614": <U.KbdSpecialKeys />,
  "615": <U.ShadcnInput />,
  "616": <U.ShadcnField />,
  "617": <U.ShadcnInputGroup />,
  "618": <U.ShadcnButtonGroup />,
  "619": <U.ShadcnInputBasic />,
  "620": <U.ShadcnInputField />,
  "621": <U.ShadcnInputFieldgroup />,
  "622": <U.ShadcnInputDisabled />,
  "623": <U.ShadcnInputInvalid />,
  "624": <U.ShadcnInputFile />,
  "625": <U.ShadcnInputInline />,
  "626": <U.ShadcnInputGrid />,
  "627": <U.ShadcnInputRequired />,
  "628": <U.ShadcnInputBadge />,
  "629": <U.ShadcnInputInputGroup />,
  "630": <U.ShadcnInputButtonGroup />,
  "631": <U.ShadcnInputForm />,
  "632": <U.ShadcnInputRtl />,
  "633": <U.ShadcnLabel />,
  "634": <U.ShadcnLabelDemo />,
  "635": <U.ShadcnLabelRtl />,
  "636": <U.ShadcnTextarea />,
  "637": <U.ShadcnTextareaDemo />,
  "638": <U.ShadcnTextareaField />,
  "639": <U.ShadcnTextareaDisabled />,
  "640": <U.ShadcnTextareaInvalid />,
  "641": <U.ShadcnTextareaButton />,
  "642": <U.ShadcnTextareaRtl />,
  "643": <U.ShadcnKbd />,
  "644": <U.ShadcnKbdDemo />,
  "645": <U.ShadcnKbdGroupExample />,
  "646": <U.ShadcnKbdButton />,
  "647": <U.ShadcnKbdTooltip />,
  "648": <U.ShadcnKbdInputGroup />,
  "649": <U.ShadcnKbdRtl />,
  "650": <U.ShadcnFieldDemo />,
  "651": <U.ShadcnFieldInput />,
  "652": <U.ShadcnFieldTextarea />,
  "653": <U.ShadcnFieldSelect />,
  "654": <U.ShadcnFieldSlider />,
  "655": <U.ShadcnFieldFieldset />,
  "656": <U.ShadcnFieldCheckbox />,
  "657": <U.ShadcnFieldRadio />,
  "658": <U.ShadcnFieldSwitch />,
  "659": <U.ShadcnFieldChoiceCard />,
  "660": <U.ShadcnFieldGroupExample />,
  "661": <U.ShadcnFieldRtl />,
  "662": <U.ShadcnInputGroup />,
  "663": <U.ShadcnInputGroupDemo />,
  "664": <U.ShadcnInputGroupInlineStart />,
  "665": <U.ShadcnInputGroupInlineEnd />,
  "666": <U.ShadcnInputGroupBlockStart />,
  "667": <U.ShadcnInputGroupBlockEnd />,
  "668": <U.ShadcnInputGroupIcon />,
  "669": <U.ShadcnInputGroupTextExample />,
  "670": <U.ShadcnInputGroupButtonExample />,
  "671": <U.ShadcnInputGroupKbd />,
  "672": <U.ShadcnInputGroupDropdown />,
  "673": <U.ShadcnInputGroupSpinner />,
  "674": <U.ShadcnInputGroupTextareaExample />,
  "675": <U.ShadcnInputGroupCustom />,
}
